[build]
  command = "pnpm build"
  publish = "out"
  
[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NODE_VERSION = "20"
  PNPM_VERSION = "8.15.1"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "noindex"
    Referrer-Policy = "strict-origin-when-cross-origin"
